version: "3.3"
services:
  node:
    image: "node:18.15.0"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - HOST=0
      #- NODE_ENV=production

networks:
  nuxt:
    driver: bridge